### ISSUE TITLE
Installation failed: linux/compiler-gcc6.h: No such file or directory

### ISSUE THREAD

**Issue by stephenfrancis** [RaumZeit/LinuxOnAcerCB5-311#10]
Hi,
Thank you for writing this project! I've realized that the locked-down Chromeos world is not for me and am longing to run a nice slim linux o/s on my Acer Chromebook.

Everything seemed to be going fine until I got to the "makepkg -si" step. Output pasted below. My machine is:
Acer Chromebook 13 CB5-311, RMN Z3ENN. 16GB flash.

Any help would be greatly appreciated!

[alarm@alarm ~]$ pwd
/home/alarm
[alarm@alarm ~]$ git clone https://github.com/RaumZeit/PKGBUILDs.git -b acer_cb_tegrak1
Cloning into 'PKGBUILDs'...
fatal: unable to access 'https://github.com/RaumZeit/PKGBUILDs.git/': Could not resolve host: github.com
[alarm@alarm ~]$ git clone https://github.com/RaumZeit/PKGBUILDs.git -b acer_cb_tegrak1
Cloning into 'PKGBUILDs'...
remote: Counting objects: 71004, done.
remote: Total 71004 (delta 0), reused 0 (delta 0), pack-reused 71004
Receiving objects: 100% (71004/71004), 36.99 MiB | 466.00 KiB/s, done.
Resolving deltas: 100% (36276/36276), done.
Checking connectivity... done.
[alarm@alarm ~]$ cd PKGBUILDs/core/linux-nyan/
[alarm@alarm linux-nyan]$ makepkg -si
==> Making package: linux-nyan 3.10.18-5 (Tue Jun  7 19:30:37 UTC 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

```
#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.
```

[sudo] password for alarm: 
resolving dependencies...
looking for conflicting packages...

Packages (7) docbook-xml-4.5-6  libxslt-1.1.29-1  bc-1.06.95-2  docbook-xsl-1.79.1-1  dtc-1.4.1-1  uboot-tools-2016.03-1  xmlto-0.0.28-1

Total Download Size:    1.36 MiB
Total Installed Size:  18.68 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 libxslt-1.1.29-1-armv7h                                                    333.1 KiB  1586K/s 00:00 [############################################################] 100%
 xmlto-0.0.28-1-armv7h                                                       23.3 KiB   583K/s 00:00 [############################################################] 100%
 docbook-xml-4.5-6-any                                                       84.0 KiB   764K/s 00:00 [############################################################] 100%
 docbook-xsl-1.79.1-1-any                                                   732.4 KiB  1786K/s 00:00 [############################################################] 100%
 bc-1.06.95-2-armv7h                                                         71.7 KiB  1792K/s 00:00 [############################################################] 100%
 dtc-1.4.1-1-armv7h                                                          55.3 KiB   790K/s 00:00 [############################################################] 100%
 uboot-tools-2016.03-1-armv7h                                                91.9 KiB  1149K/s 00:00 [############################################################] 100%
(7/7) checking keys in keyring                                                                       [############################################################] 100%
(7/7) checking package integrity                                                                     [############################################################] 100%
(7/7) loading package files                                                                          [############################################################] 100%
(7/7) checking for file conflicts                                                                    [############################################################] 100%
(7/7) checking available disk space                                                                  [############################################################] 100%
:: Processing package changes...
(1/7) installing libxslt                                                                             [############################################################] 100%
(2/7) installing xmlto                                                                               [############################################################] 100%
(3/7) installing docbook-xml                                                                         [############################################################] 100%
(4/7) installing docbook-xsl                                                                         [############################################################] 100%
(5/7) installing bc                                                                                  [############################################################] 100%
(6/7) installing uboot-tools                                                                         [############################################################] 100%
(7/7) installing dtc                                                                                 [############################################################] 100%
:: Running post-transaction hooks...
(1/2) Updating manpage index...
(2/2) Updating the info directory file...
==> Retrieving sources...
  -> Downloading ed20e6baa678327b174bc972f52408438c51e387.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  119M    0  119M    0     0  1726k      0 --:--:--  0:01:10 --:--:-- 1622k
  -> Downloading sd8787_uapsta_cros.bin...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    515      0 --:--:-- --:--:-- --:--:--   516
100  402k  100  402k    0     0   117k      0  0:00:03  0:00:03 --:--:--  136k
  -> Downloading sd8797_uapsta_cros.bin...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    406      0 --:--:-- --:--:-- --:--:--   407
100  449k  100  449k    0     0   142k      0  0:00:03  0:00:03 --:--:--  216k
  -> Downloading sd8897_uapsta_cros.bin...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    352      0 --:--:-- --:--:-- --:--:--   353
100  680k  100  680k    0     0   169k      0  0:00:04  0:00:04 --:--:--  221k
  -> Downloading xhci-firmware-2015.05.06.00.00.tbz2...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79564  100 79564    0     0   187k      0 --:--:-- --:--:-- --:--:--  187k
  -> Found config
  -> Found 0001-mwifiex-do-not-create-AP-and-P2P-interfaces-upon-dri.patch
  -> Found 0002-use-chromiumos-mwifiex-drivers.patch
  -> Found 0003-kernel-add-support-for-gcc-5.patch
  -> Found 0004-wlan-ng-fix-sparse-warning-in-prism2fw.c.patch
  -> Found 0005-netfilter-nfnetlink_cthelper-Remove-const-and-to-avo.patch
  -> Found 0006-zd1201-Drop-the-node-parameter-from-the-hlist-iterat.patch
  -> Found 0007-Fix-reversed-logic-in-drivers-md-md.c.patch
  -> Found 0008-Fix-compilation-with-stricter-GCC5.patch
  -> Found kernel-nyan.its
  -> Found kernel.keyblock
  -> Found kernel_data_key.vbprivk
  -> Found cmdline
==> Validating source files with sha256sums...
    ed20e6baa678327b174bc972f52408438c51e387.tar.gz ... Skipped
    sd8787_uapsta_cros.bin ... Passed
    sd8797_uapsta_cros.bin ... Passed
    sd8897_uapsta_cros.bin ... Passed
    xhci-firmware-2015.05.06.00.00.tbz2 ... Passed
    config ... Passed
    0001-mwifiex-do-not-create-AP-and-P2P-interfaces-upon-dri.patch ... Passed
    0002-use-chromiumos-mwifiex-drivers.patch ... Passed
    0003-kernel-add-support-for-gcc-5.patch ... Passed
    0004-wlan-ng-fix-sparse-warning-in-prism2fw.c.patch ... Passed
    0005-netfilter-nfnetlink_cthelper-Remove-const-and-to-avo.patch ... Passed
    0006-zd1201-Drop-the-node-parameter-from-the-hlist-iterat.patch ... Passed
    0007-Fix-reversed-logic-in-drivers-md-md.c.patch ... Passed
    0008-Fix-compilation-with-stricter-GCC5.patch ... Passed
    kernel-nyan.its ... Passed
    kernel.keyblock ... Passed
    kernel_data_key.vbprivk ... Passed
    cmdline ... Passed
==> Extracting sources...
  -> Extracting ed20e6baa678327b174bc972f52408438c51e387.tar.gz with bsdtar
  -> Extracting xhci-firmware-2015.05.06.00.00.tbz2 with bsdtar
==> Starting prepare()...
patching file drivers/net/wireless-3.8/mwifiex/main.c
patching file drivers/net/wireless-3.8/mwifiex/sdio.h
patching file include/linux/compiler-gcc5.h
patching file drivers/staging/wlan-ng/prism2fw.c
patching file net/netfilter/nfnetlink_cthelper.c
patching file drivers/net/wireless-3.8/zd1201.c
patching file drivers/md/md.c
patching file arch/arm/include/asm/ftrace.h
patching file arch/arm/kernel/return_address.c
patching file lib/decompress_unlzo.c
patching file mm/rmap.c
==> Starting build()...
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
In file included from scripts/kconfig/zconf.tab.c:2503:0:
scripts/kconfig/menu.c: In function 'get_symbol_str':
scripts/kconfig/menu.c:567:18: warning: 'jump' may be used uninitialized in this function [-Wmaybe-uninitialized]
     jump->offset = r->len - 1;
     ~~~~~~~~~~~~~^~~~~~~~~~~~
scripts/kconfig/menu.c:528:19: note: 'jump' was declared here
  struct jump_key _jump;
                   ^~~~
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf --silentoldconfig Kconfig
  WRAP    arch/arm/include/generated/asm/auxvec.h
  WRAP    arch/arm/include/generated/asm/bitsperlong.h
  WRAP    arch/arm/include/generated/asm/cputime.h
  WRAP    arch/arm/include/generated/asm/current.h
  WRAP    arch/arm/include/generated/asm/emergency-restart.h
  WRAP    arch/arm/include/generated/asm/errno.h
  WRAP    arch/arm/include/generated/asm/exec.h
  WRAP    arch/arm/include/generated/asm/ioctl.h
  WRAP    arch/arm/include/generated/asm/ipcbuf.h
  WRAP    arch/arm/include/generated/asm/irq_regs.h
  WRAP    arch/arm/include/generated/asm/kdebug.h
  WRAP    arch/arm/include/generated/asm/local.h
  WRAP    arch/arm/include/generated/asm/local64.h
  WRAP    arch/arm/include/generated/asm/msgbuf.h
  WRAP    arch/arm/include/generated/asm/param.h
  WRAP    arch/arm/include/generated/asm/parport.h
  WRAP    arch/arm/include/generated/asm/poll.h
  WRAP    arch/arm/include/generated/asm/resource.h
  WRAP    arch/arm/include/generated/asm/sections.h
  WRAP    arch/arm/include/generated/asm/segment.h
  WRAP    arch/arm/include/generated/asm/sembuf.h
  WRAP    arch/arm/include/generated/asm/serial.h
  WRAP    arch/arm/include/generated/asm/shmbuf.h
  WRAP    arch/arm/include/generated/asm/siginfo.h
  WRAP    arch/arm/include/generated/asm/sizes.h
  WRAP    arch/arm/include/generated/asm/socket.h
  WRAP    arch/arm/include/generated/asm/sockios.h
  WRAP    arch/arm/include/generated/asm/termbits.h
  WRAP    arch/arm/include/generated/asm/termios.h
  WRAP    arch/arm/include/generated/asm/timex.h
  WRAP    arch/arm/include/generated/asm/trace_clock.h
  WRAP    arch/arm/include/generated/asm/types.h
  WRAP    arch/arm/include/generated/asm/unaligned.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  Generating include/generated/mach-types.h
  CC      kernel/bounds.s
In file included from include/linux/compiler.h:54:0,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /home/alarm/PKGBUILDs/core/linux-nyan/src/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/page-flags.h:8,
                 from kernel/bounds.c:9:
include/linux/compiler-gcc.h:103:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(**GNUC**)
                              ^
compilation terminated.
/home/alarm/PKGBUILDs/core/linux-nyan/src/./Kbuild:35: recipe for target 'kernel/bounds.s' failed
make[1]: *_\* [kernel/bounds.s] Error 1
Makefile:847: recipe for target 'prepare0' failed
make: **\* [prepare0] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
[alarm@alarm linux-nyan]$

**Comment by RaumZeit** [comment]
The gcc6 compilation problem should be fixed latest HEAD of linux-nyan package in my PKGBUILDs repo master branch. See also https://github.com/RaumZeit/PKGBUILDs/commit/92e253fab6b0c215dead4057a0e6660e97faf5d0

**Comment by stephenfrancis** [comment]
Hi,
Thanks for working on this issue so quickly. Unfortunately, I tried again just now and had the same problem again. Looking at the PKGBUILDs repo, it seems that your commit was to the master branch.

I'm following instructions which say:
git clone https://github.com/RaumZeit/PKGBUILDs.git -b acer_cb_tegrak1

which checks out the acer_cb_tegrak1 branch, rather than master, right?

I really appreciate your help,
Stephen

**Comment by RaumZeit** [comment]
I already merged the acer_cb_tegrak1 branch into my master PKBBUILDs repo some time ago and applied most of the updates on master rather than acer_cb_tegrak1 since then. The install instructions in this repo have already been updated and I just updated the instructions at my website. Please try using the master branch instead to build linux-nyan-3.10.18-9, which I successfully compiled with gcc6 yesterday.
