### ISSUE TITLE
Can not connect to WiFi

### ISSUE THREAD

**Issue by lovedheart** [RaumZeit/LinuxOnAcerCB5-311#12]
Hi,

I just install with the sh script. It can boot into archlinux, but I can not connect it to router

**Comment by RaumZeit** [comment]
What exactly is not working? Can you elaborate a little what your actual problem is?

**Comment by lovedheart** [comment]
I choose one of the network list and click it. But nothing happens. No dialog is shown to require PSK

**Comment by RaumZeit** [comment]
This sounds like gnome-keyring is not running, try installing it along with seahorse to manage your keys and passwords. Make sure gnome-keyring gets started whenever you login to XFCE4: Enable `Settings/"Session and Startup"/Advanced/"Launch GNOME Services on startup"`
and all Gnome Keyring related services in
`Settings/"Session and Startup/"Application Autostart"`. As far as I remember, the user also needs to be in the `network` group to get Network Manager working right.
See also: https://wiki.archlinux.org/index.php/NetworkManager#No_prompt_for_password_of_secured_Wi-Fi_networks
