### ISSUE TITLE
[OT] edits for the function keys

### ISSUE THREAD

**Issue by reey** [RaumZeit/LinuxOnAcerCB5-311#14]
This is no issue with your project here, but with the description over here: https://www.tbi.univie.ac.at/~ronny/acer-cb5-311.html

I also have the Acer CB5-311 and to be able to use the refresh/reload function key right, you need to change the XF86Refresh to XF86Reload. If not pages opened with chromium will not be refreshed.

Thanks for your great work :)

**Comment by RaumZeit** [comment]
Thanks for the hint! I've fixed that and also included the config files and scripts to this repository
