### ISSUE TITLE
Post-Install Hang On Boot

### ISSUE THREAD

**Issue by KenDickey** [RaumZeit/LinuxOnAcerCB5-311#19]
Greetings,

First, thanks much for all the great work pulling this together -- way beyond my skill level!

Unfortunately, the instructions are not working for me.

Everything looks good until the attempt to reboot into Arch Linux Arm.  Things start well but then the system hangs.

Some info from the screen:
vvv========vvv
...
Failed to start Light Display Manager
...
Reached target Graphical Display Interface
...
mwifiex_sdio ...   (link not ready)
... info scan: num passes = 4
    ...

^^^========^^^
The keyboard is unresponsive except for PWR.

I tried mounting /dev/mmcblk0p7 and adding a file ("wireless_wpa") to /etc/netctl/ with the WPA key.

I also took a look at /var/log/lightdm/lightdm.log
vvv========vvv
... 
new seat added for logid: seat0
...
could not run plymouth --ping
Using VT 7
...
X Server: 0: Can't launch X server X, not found in path
...
Failed to start seat: seat0
^^^=======^^^

Any help is appreciated!
-KenD        [Ken (dor) Dickey (at) Whidbey (dot) com]

**Comment by RaumZeit** [comment]
There has been a problem during xorg downgrade, which is fixed now.
Everything should be working as expected since commit 50b286b6ddb6a17cad6efd0e2be1e658a69013aa

Please re-open the issue if the problem persists for you
