### ISSUE TITLE
HDMI audio pass-through

### ISSUE THREAD

**Issue by bmalnersic** [RaumZeit/LinuxOnAcerCB5-311#6]
Hi,

I had some trouble setting up HDMI audio pass-through. Unfortunately I had no time to test what is described on this web page:
[Jetson HDMI Audio Limitations ?](https://devtalk.nvidia.com/default/topic/779272/jetson-hdmi-audio-limitations-/)
[PulseAudio Passthrough Mode](http://kodi.wiki/view/PulseAudio#Passthrough_Mode)
So this is currently more of a reminder for me to test this as soon as possible. 

Best regards,

```
Blaz
```

**Comment by RaumZeit** [comment]
I just tested HDMI audio yesterday and it works fine. One has, however, to do some things manually for pulseaudio to acknowledge the HDMI sink. Please refer to https://wiki.archlinux.org/index.php/PulseAudio/Examples#HDMI_output_configuration
HDMI audio output is hw0,3 for my Acer CB5-311, it might be different for others.
A detailed instruction will be included in my HowTo at http://www.tbi.univie.ac.at/~ronny/acer-cb5-311.html soon
